# write docker compose file with frontend and backend
version: '3'
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
